AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'Gemfile*'
    - 'bin/**/*'
    - 'test/**/*'
    - 'Rakefile'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'vendor/**/*'
    - 'Guardfile'

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - 'describe'
    - 'context'
    - 'define'
    - 'trait'
    - 'factory'

Metrics/LineLength:
  IgnoredPatterns:
    - '\w*it.+do'
    - '\w*context.+do'

Style/Lambda:
    Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 25
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method
